version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Release
- Debug
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  verbosity: minimal
after_build:
- 7z a OBeautifulCode.String.zip %APPVEYOR_BUILD_FOLDER%\OBeautifulCode.String\bin\%CONFIGURATION%\*.* -r
- ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/NaosProject/Naos.Powershell/master/Build/Nuget-Functions.ps1', "$($env:appveyor_build_folder)\Nuget-Functions.ps1")
- ps: . "$($env:appveyor_build_folder)\Nuget-Functions.ps1"
- ps: ls . -filter *.recipe-nuspec -recurse | %{Nuget-OverrideNuSpecIntoNewFile -templateFile "$($env:appveyor_build_folder)\OBeautifulCode.String\OBeautifulCode.String.template-nuspec" -overrideFile $_.FullName -targetFile $_.FullName.Replace('.recipe-nuspec','.nuspec')}
- ps: $version = Nuget-CreatePreReleaseSupportedVersion -version $env:appveyor_build_version -branchName $env:appveyor_repo_branch
- ps: ls . -filter *.nuspec -recurse | %{nuget pack $_.FullName -Version $version }
artifacts:
- path: OBeautifulCode.String.zip
- path: '*.nupkg'
- path: Nuget-Functions.ps1
deploy:
  provider: NuGet
  api_key:
    secure: aUaOAaFmJX9VJGINuxJ86ljfbXzi6I748PR0zL8VdZElrdh7C0sbPoFRKl8eciDY
  skip_symbols: true
  artifact: /.*\.nupkg/